/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Layout from "../../../components/layout";
import Header from "../../../components/header";

import finallogo from "../../../assets/logo.png";
import loanrejection from "../../../assets/Empty wallet.png";

import Image from "next/image";

export default function Home() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Dashboard</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA]">
                    {/* Change props to suit page*/}
                    <Header title={"Mortgage Requests"} number={21} />
                    {/* Bottom menu */}
                    <div className="flex items-center bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">
                            Mortgage Requests/ Loan Processing
                        </div>
                    </div>

                    <div className="w-[600px] h-[900px] m-28 bg-white">
                        <Image
                            className="pt-[30px] ml-[270px]"
                            src={finallogo}
                            width={76}
                            alt={"Homehub logo"}
                        />
                        <h1 className="mt-[30px] text-center font-black leading-[60px] text-3xl">
                            Loan Rejection
                        </h1>

                        <Image
                            className="pt-[30px] ml-[225px]"
                            src={loanrejection}
                            width={193}
                            alt={"Loan rejection image"}
                        />

                        {/* Rejection message */}
                        <p className="w-[473px] pt-8 pl-[9rem] leading-[17px] text-[12px] ">
                            Hello Hamida,
                            <br />
                            <br />
                            This mail is to notify you about the rejection of
                            your loan request that you submitted to Zenith Bank.
                            Unfortunately, you failed to fulfil the criteria
                            that is prescribed for the loan approval at our Bank
                            or the credentials and assets that you provided
                            failed to be verified by our verification team.
                            Thanks for showing interest in our loan scheme.
                            <br />
                            <br />
                            You may contact the concerned branch for further
                            queries if any.
                            <br />
                            <br />
                            Loan Department
                            <br />
                            Zenith Bank.
                            <br />
                            <br />
                            <br />
                            If you need help setting up, the Homehub customer
                            Service team is standing by. Reach out by sending an
                            email to customer@homehub.com
                            <br />
                            <br />
                            The Homehub Team
                        </p>

                        <hr className="w-[478px] h-[1px] mx-auto my-1 bg-[#CDCDCFCC] border-0 rounded md:my-5 dark:bg-gray-700"></hr>

                        <p className="text-center pb-[25px] text-[12px]">
                            Sent with love from homehub.com
                        </p>
                        <p className="text-center text-[12px]  leading-[18px]">
                            If you are having issues clicking the get started
                            button, copy and paste the URL below in your web
                            browser. https://homehub.com/get_started
                        </p>

                        <p className="text-center text-[12px] pt-[20px]">
                            (c) 2022 Homehub . All Rights Reserveed
                        </p>
                    </div>
                </main>
            </Layout>
        </>
    );
}
