/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import finallogo from "../../../assets/logo.png";
import congratsimage from "../../../assets/Loan approved.png";
import Layout from "../../../components/layout";
import Header from "../../../components/header";

import Image from "next/image";

export default function LoanApproval() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Dashboard</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA]">
                    {/* Change props to suit page*/}
                    <Header title={"Mortgage Requests"} number={21} />
                    {/* Bottom menu */}
                    <div className="flex items-center bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">
                            Mortgage Requests/ Loan Processing
                        </div>
                    </div>

                    <div className="w-[600px] h-[880px] mb-20 ml-60 bg-white">
                        <Image
                            className="pt-[30px] ml-[270px]"
                            src={finallogo}
                            width={76}
                            alt={"Homehub logo"}
                        />
                        <h1 className="mt-[30px] text-center font-black leading-[60px] text-3xl">
                            Congratulations!
                        </h1>

                        <Image
                            className="pt-[30px] ml-[225px]"
                            src={congratsimage}
                            width={193}
                            alt={"Homehub logo"}
                        />

                        {/* loan approval message */}
                        <p className="w-[473px] pt-8 pl-[9rem] leading-[17px] text-[12px] ">
                            Hello Hamida,
                            <br />
                            <br />
                            Your loan reqest has been pre-approved by Zenith
                            Bank. Kindly make sure you go through the
                            pre-approval letter and contract attached to this
                            mail. It contains information about the terms and
                            conditions of your loan.
                            <br />
                            Please return to this email with the completed form
                            after filling it out and signing it, and also upload
                            a copy to the Homehub app.
                            <br />
                            <br />
                            Loan Department
                            <br />
                            Zenith Bank.
                            <br />
                            <br />
                            <br />
                            If you need help setting up, the Homehub customer
                            Service team is standing by. Reach out by sending an
                            email to customer@homehub.com
                        </p>

                        {/* horizontal divide */}
                        <hr className="w-[478px] h-[1px] mx-auto my-4 bg-[#CDCDCFCC] border-0 rounded md:my-10 dark:bg-gray-700"></hr>

                        <p className="text-center pb-[25px] text-[12px]">
                            Sent with love from homehub.com
                        </p>
                        <p className="text-center text-[12px]  leading-[18px] max-w-[433px]">
                            If you are having issues clicking the get started
                            button, copy and paste the URL below in your web
                            browser. https://homehub.com/get_started
                        </p>

                        <p className="text-center text-[12px] pt-[20px]">
                            (c) 2022 Homehub . All Rights Reserved
                        </p>
                    </div>
                </main>
            </Layout>
        </>
    );
}
