/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import Layout from "../../../components/layout";
import Header from "../../../components/header";
export default function LoanProcessing() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Dashboard</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] xg:min-h-screen">
                    {/* Change props to suit page*/}
                    <Header title={"Mortgage Requests"} number={21} />
                    {/* Bottom menu */}
                    <div className="flex items-center bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">
                            Mortgage Requests/{" "}
                            <span className="text-black">Loan Processing</span>
                        </div>
                    </div>

                    <p className="text-sm font-semibold mx-8 px-8 py-6">
                        Schedule a mortgage interview with clients in person,
                        virtual or on phone.
                    </p>

                    <div className=" pt-3 mb-20 px-[5rem]">
                        <Tabs>
                            <div className="flex items-end mb-4 h-[4.6rem] justify-between">
                                {/* tabs */}
                                <TabList className="flex flex-row gap-x-20 ">
                                    <Tab className="active:border-b underline-offset-8 hover:bg-gray-200 text-sm focus:underline text-[#828187] font-semibold focus:decoration-[#FA790F] focus:text-[#FA790F]">
                                        Pending
                                    </Tab>
                                    <Tab className="active:border-b text-sm focus:underline text-[#828187] focus:decoration-[#FA790F] font-semibold underline-offset-8 focus:text-[#FA790F]">
                                        Appointments
                                    </Tab>
                                </TabList>

                                <div>
                                    <form className="flex items-center gap-x-4">
                                        {/* First search field */}
                                        <label
                                            htmlFor="simple-search"
                                            className="sr-only"
                                        >
                                            Search
                                        </label>
                                        <div className="relative w-full">
                                            <div className="absolute inset-y-0 left-0 flex items-center pl-3 text-xs text-gray-500">
                                                Sort By:
                                            </div>
                                            <input
                                                type="text"
                                                id="simple-search"
                                                className="bg-white border border-gray-300 text-black text-sm rounded-lg focus:ring-[#FA790F] placeholder-black focus:border-[#FA790F] block w-full pl-14 p-2.5"
                                                placeholder="Month"
                                                required
                                            />
                                        </div>

                                        {/* Second search Field */}
                                        <label
                                            htmlFor="simple-search"
                                            className="sr-only"
                                        >
                                            Search
                                        </label>
                                        <div className="relative w-full">
                                            <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                                <svg
                                                    aria-hidden="true"
                                                    className="w-5 h-5 text-gray-500 dark:text-gray-400"
                                                    fill="currentColor"
                                                    viewBox="0 0 20 20"
                                                    xmlns="http://www.w3.org/2000/svg"
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                                        clipRule="evenodd"
                                                    ></path>
                                                </svg>
                                            </div>
                                            <input
                                                type="text"
                                                id="simple-search"
                                                className="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[#FA790F] focus:border-[#FA790F] block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#FA790F] dark:focus:border-[#FA790F]"
                                                placeholder="Search Item"
                                                required
                                            />
                                        </div>
                                    </form>
                                </div>
                            </div>

                            {/* Pending Tab */}
                            <TabPanel>
                                <div className="relative overflow-x-auto shadow-md bg-white sm:rounded-t-md">
                                    <table className="w-full text-left text-sm text-gray-500 ">
                                        <thead className="bg-[#FDF2EA] text-xs text-[#747A80]">
                                            <tr>
                                                <th
                                                    scope="col"
                                                    className="p-4"
                                                ></th>

                                                <th
                                                    scope="col"
                                                    className="py-3"
                                                >
                                                    Name
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Amount(GHC)
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Phone Number
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Status
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Action
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                ></th>
                                            </tr>
                                        </thead>

                                        <tbody className="text-[#2E2D37]">
                                            <tr className="border-b bg-white hover:bg-gray-50">
                                                <td className="w-4 p-4">
                                                    <div className="flex items-center">
                                                        <input
                                                            id="checkbox-table-1"
                                                            type="checkbox"
                                                            className="h-4 w-4 rounded  bg-gray-100 text-[#FA790F]"
                                                        />
                                                        <label
                                                            htmlFor="checkbox-table-1"
                                                            className="sr-only"
                                                        >
                                                            checkbox
                                                        </label>
                                                    </div>
                                                </td>
                                                <th
                                                    scope="row"
                                                    className="justify-between mt-4 whitespace-nowrap py-4 font-medium text-gray-900"
                                                >
                                                    <p>Ama Yeboah</p>
                                                    <p className="text-[#6568A4] hover:underline text-xs">
                                                        example@gmail.com
                                                    </p>
                                                </th>
                                                <td className="px-6 py-6">
                                                    <p>3000.00</p>
                                                </td>
                                                <td className="px-6 py-4">
                                                    +233 567 000 0001
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <p className="pb-2 font-medium">
                                                        Submitted
                                                    </p>
                                                    <p className="text-[#828187]">
                                                        on 23/04/2022
                                                    </p>
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <button
                                                        type="button"
                                                        className="px-3 py-2 text-xs font-medium text-center text-white bg-[#D0650D] rounded-lg hover:bg-[#fa790fc5] focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-[#D0650D] dark:hover:bg-[#fa790fc5] dark:focus:ring-blue-800"
                                                    >
                                                        Schedule Meeting
                                                    </button>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        id="dropdownMenuIconButton"
                                                        data-dropdown-toggle="dropdownDots"
                                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                                                        type="button"
                                                    >
                                                        <svg
                                                            className="w-6 h-6"
                                                            aria-hidden="true"
                                                            fill="currentColor"
                                                            viewBox="0 0 20 20"
                                                            xmlns="http://www.w3.org/2000/svg"
                                                        >
                                                            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path>
                                                        </svg>
                                                    </button>

                                                    <div
                                                        id="dropdownDots"
                                                        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                                                    >
                                                        <ul
                                                            className="py-2 text-sm text-gray-700 dark:text-gray-200"
                                                            aria-labelledby="dropdownMenuIconButton"
                                                        >
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Dashboard
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Settings
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Earnings
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>

                                            {/* Second row */}
                                            <tr className="border-b bg-white hover:bg-gray-50">
                                                <td className="w-4 p-4">
                                                    <div className="flex items-center">
                                                        <input
                                                            id="checkbox-table-1"
                                                            type="checkbox"
                                                            className="h-4 w-4 rounded  bg-gray-100 text-[#FA790F]"
                                                        />
                                                        <label
                                                            htmlFor="checkbox-table-1"
                                                            className="sr-only"
                                                        >
                                                            checkbox
                                                        </label>
                                                    </div>
                                                </td>
                                                <th
                                                    scope="row"
                                                    className="justify-between mt-4 whitespace-nowrap py-4 font-medium text-gray-900"
                                                >
                                                    <p>Kofi Ansah</p>
                                                    <p className="hover:underline text-[#6568A4] text-xs">
                                                        example@gmail.com
                                                    </p>
                                                </th>
                                                <td className="px-6 py-6">
                                                    <p>3000.00</p>
                                                </td>
                                                <td className="px-6 py-4">
                                                    +233 567 000 0001
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <p className="pb-2 font-medium">
                                                        Submitted
                                                    </p>
                                                    <p className="text-[#828187]">
                                                        on 23/04/2022
                                                    </p>
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <button
                                                        type="button"
                                                        className="px-3 py-2 text-xs font-medium text-center text-white bg-[#D0650D] rounded-lg hover:bg-[#fa790fc5] focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-[#D0650D] dark:hover:bg-[#fa790fc5] dark:focus:ring-blue-800"
                                                    >
                                                        Schedule Meeting
                                                    </button>
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <button
                                                        id="dropdownMenuIconButton"
                                                        data-dropdown-toggle="dropdownDots"
                                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                                                        type="button"
                                                    >
                                                        <svg
                                                            className="w-6 h-6"
                                                            aria-hidden="true"
                                                            fill="currentColor"
                                                            viewBox="0 0 20 20"
                                                            xmlns="http://www.w3.org/2000/svg"
                                                        >
                                                            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path>
                                                        </svg>
                                                    </button>

                                                    <div
                                                        id="dropdownDots"
                                                        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                                                    >
                                                        <ul
                                                            className="py-2 text-sm text-gray-700 dark:text-gray-200"
                                                            aria-labelledby="dropdownMenuIconButton"
                                                        >
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Dashboard
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Settings
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Earnings
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>

                                                {/* Third row */}
                                            </tr>
                                            <tr className="border-b bg-white hover:bg-gray-50">
                                                <td className="w-4 p-4">
                                                    <div className="flex items-center">
                                                        <input
                                                            id="checkbox-table-1"
                                                            type="checkbox"
                                                            className="h-4 w-4 rounded  bg-gray-100 text-[#FA790F]"
                                                        />
                                                        <label
                                                            htmlFor="checkbox-table-1"
                                                            className="sr-only"
                                                        >
                                                            checkbox
                                                        </label>
                                                    </div>
                                                </td>
                                                <th
                                                    scope="row"
                                                    className="justify-between mt-4 whitespace-nowrap py-4 font-medium text-gray-900"
                                                >
                                                    <p>Hamida Mahama</p>
                                                    <p className="text-[#6568A4] text-xs">
                                                        example@gmail.com
                                                    </p>
                                                </th>
                                                <td className="px-6 py-6">
                                                    <p>3000.00</p>
                                                </td>
                                                <td className="px-6 py-4">
                                                    +233 567 000 0001
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <p className="font-medium pb-2">
                                                        Submitted
                                                    </p>
                                                    <p className="text-[#828187]">
                                                        on 23/04/2022
                                                    </p>
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <button
                                                        type="button"
                                                        className="px-3 py-2 text-xs font-medium text-center text-white bg-[#D0650D] rounded-lg hover:bg-[#fa790fc5] focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-[#fa790fc5] dark:hover:bg-[#D0650D] dark:focus:ring-blue-800"
                                                    >
                                                        Schedule Meeting
                                                    </button>
                                                </td>
                                                <td className="pl-6 py-4">
                                                    <button
                                                        id="dropdownMenuIconButton"
                                                        data-dropdown-toggle="dropdownDots"
                                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                                                        type="button"
                                                    >
                                                        <svg
                                                            className="w-6 h-6"
                                                            aria-hidden="true"
                                                            fill="currentColor"
                                                            viewBox="0 0 20 20"
                                                            xmlns="http://www.w3.org/2000/svg"
                                                        >
                                                            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path>
                                                        </svg>
                                                    </button>

                                                    <div
                                                        id="dropdownDots"
                                                        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                                                    >
                                                        <ul
                                                            className="py-2 text-sm text-gray-700 dark:text-gray-200"
                                                            aria-labelledby="dropdownMenuIconButton"
                                                        >
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Dashboard
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Settings
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Earnings
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </TabPanel>

                            {/* Appintment tab */}
                            <TabPanel>
                                <div className="relative overflow-x-auto shadow-md bg-white sm:rounded-t-md">
                                    <table className="w-full text-left text-sm text-gray-500 ">
                                        <thead className="bg-[#FDF2EA] text-xs text-[#747A80]">
                                            <tr>
                                                <th
                                                    scope="col"
                                                    className="p-4"
                                                ></th>

                                                <th
                                                    scope="col"
                                                    className="py-3"
                                                >
                                                    Name
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Date
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Time
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Status
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                >
                                                    Action
                                                </th>
                                                <th
                                                    scope="col"
                                                    className="px-6 py-3"
                                                ></th>
                                            </tr>
                                        </thead>

                                        <tbody className="text-[#2E2D37]">
                                            {/* First row */}
                                            <tr className="border-b bg-white hover:bg-gray-50">
                                                <td className="w-4 p-4">
                                                    <div className="flex items-center">
                                                        <input
                                                            id="checkbox-table-1"
                                                            type="checkbox"
                                                            className="h-4 w-4 rounded  bg-gray-100 text-[#FA790F]"
                                                        />
                                                        <label
                                                            htmlFor="checkbox-table-1"
                                                            className="sr-only"
                                                        >
                                                            checkbox
                                                        </label>
                                                    </div>
                                                </td>
                                                <th
                                                    scope="row"
                                                    className="justify-between mt-4 whitespace-nowrap py-4 font-medium text-gray-900"
                                                >
                                                    <p>Ama Yeboah</p>
                                                    <p className="hover:underline text-[#6568A4] text-xs">
                                                        example@gmail.com
                                                    </p>
                                                </th>
                                                <td className="px-6 py-6">
                                                    <p>
                                                        Friday, 13th June 2022
                                                    </p>
                                                </td>
                                                <td className="px-6 py-4">
                                                    4:00 PM
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <p className="font-medium pb-2">
                                                        Submitted
                                                    </p>
                                                    <p className="text-[#828187]">
                                                        on 23/04/2022
                                                    </p>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        type="button"
                                                        className="text-[#FF9900] hover:text-white border border-[#FF9900] hover:bg-[#FF9900] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded text-sm px-5 py-1 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                                                    >
                                                        Reschedule
                                                    </button>
                                                    <br />
                                                    <a className=" text-[#0C17DC] text-sm font-medium hover:text-[#4b53eb]">
                                                        View Appointment
                                                    </a>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        id="dropdownMenuIconButton"
                                                        data-dropdown-toggle="dropdownDots"
                                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                                                        type="button"
                                                    >
                                                        <svg
                                                            className="w-6 h-6"
                                                            aria-hidden="true"
                                                            fill="currentColor"
                                                            viewBox="0 0 20 20"
                                                            xmlns="http://www.w3.org/2000/svg"
                                                        >
                                                            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path>
                                                        </svg>
                                                    </button>

                                                    <div
                                                        id="dropdownDots"
                                                        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                                                    >
                                                        <ul
                                                            className="py-2 text-sm text-gray-700 dark:text-gray-200"
                                                            aria-labelledby="dropdownMenuIconButton"
                                                        >
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Dashboard
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Settings
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Earnings
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>

                                            {/* Second row */}
                                            <tr className="border-b bg-white hover:bg-gray-50">
                                                <td className="w-4 p-4">
                                                    <div className="flex items-center">
                                                        <input
                                                            id="checkbox-table-1"
                                                            type="checkbox"
                                                            className="h-4 w-4 rounded  bg-gray-100 text-[#FA790F]"
                                                        />
                                                        <label
                                                            htmlFor="checkbox-table-1"
                                                            className="sr-only"
                                                        >
                                                            checkbox
                                                        </label>
                                                    </div>
                                                </td>
                                                <th
                                                    scope="row"
                                                    className="justify-between mt-4 whitespace-nowrap py-4 font-medium text-gray-900"
                                                >
                                                    <p>Kofi Ansah</p>
                                                    <p className="text-[#6568A4] hover:underline text-xs">
                                                        example@gmail.com
                                                    </p>
                                                </th>
                                                <td className="px-6 py-6">
                                                    <p>
                                                        Wednesday, 11th June
                                                        2022
                                                    </p>
                                                </td>
                                                <td className="px-6 py-4">
                                                    12:00 PM
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <p className="font-medium pb-2">
                                                        Submitted
                                                    </p>
                                                    <p className="text-[#828187]">
                                                        on 23/04/2022
                                                    </p>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        type="button"
                                                        className="text-[#FF9900] hover:text-white border border-[#FF9900] hover:bg-[#FF9900] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded text-sm px-5 py-1 text-center mr-2 mb-2 dark:border-[#FF9900] dark:text-[#FF9900] dark:hover:text-white dark:hover:bg-[#FF9900] dark:focus:ring-[#FF9900]"
                                                    >
                                                        Reschedule
                                                    </button>
                                                    <br />

                                                    <a
                                                        href="#"
                                                        className=" text-[#0C17DC] text-sm font-medium hover:text-[#4b53eb]"
                                                    >
                                                        View Appointment
                                                    </a>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        id="dropdownMenuIconButton"
                                                        data-dropdown-toggle="dropdownDots"
                                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                                                        type="button"
                                                    >
                                                        <svg
                                                            className="w-6 h-6"
                                                            aria-hidden="true"
                                                            fill="currentColor"
                                                            viewBox="0 0 20 20"
                                                            xmlns="http://www.w3.org/2000/svg"
                                                        >
                                                            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path>
                                                        </svg>
                                                    </button>

                                                    <div
                                                        id="dropdownDots"
                                                        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                                                    >
                                                        <ul
                                                            className="py-2 text-sm text-gray-700 dark:text-gray-200"
                                                            aria-labelledby="dropdownMenuIconButton"
                                                        >
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Dashboard
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Settings
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Earnings
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>

                                                {/* Third row */}
                                            </tr>
                                            <tr className="border-b bg-white hover:bg-gray-50">
                                                <td className="w-4 p-4">
                                                    <div className="flex items-center">
                                                        <input
                                                            id="checkbox-table-1"
                                                            type="checkbox"
                                                            className="h-4 w-4 rounded  bg-gray-100 text-[#FA790F]"
                                                        />
                                                        <label
                                                            htmlFor="checkbox-table-1"
                                                            className="sr-only"
                                                        >
                                                            checkbox
                                                        </label>
                                                    </div>
                                                </td>
                                                <th
                                                    scope="row"
                                                    className="justify-between mt-4 whitespace-nowrap py-4 font-medium text-gray-900"
                                                >
                                                    <p>Hamida Mahama</p>
                                                    <p className="text-[#6568A4] hover:underline text-xs">
                                                        example@gmail.com
                                                    </p>
                                                </th>
                                                <td className="px-6 py-6">
                                                    <p>
                                                        Friday, 13th June 2022
                                                    </p>
                                                </td>
                                                <td className="px-6 py-4">
                                                    1:00 PM
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <p className="font-medium pb-2">
                                                        Submitted
                                                    </p>
                                                    <p className="text-[#828187]">
                                                        on 23/04/2022
                                                    </p>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        type="button"
                                                        className="text-[#FF9900] hover:text-white border border-[#FF9900] hover:bg-[#FF9900] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded text-sm px-5 py-1 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                                                    >
                                                        Reschedule
                                                    </button>
                                                    <br />
                                                    <a
                                                        href="#"
                                                        className=" text-[#0C17DC] text-sm font-medium hover:text-[#4b53eb]"
                                                    >
                                                        View Appointment
                                                    </a>
                                                </td>

                                                <td className="pl-6 py-4">
                                                    <button
                                                        id="dropdownMenuIconButton"
                                                        data-dropdown-toggle="dropdownDots"
                                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                                                        type="button"
                                                    >
                                                        <svg
                                                            className="w-6 h-6"
                                                            aria-hidden="true"
                                                            fill="currentColor"
                                                            viewBox="0 0 20 20"
                                                            xmlns="http://www.w3.org/2000/svg"
                                                        >
                                                            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path>
                                                        </svg>
                                                    </button>

                                                    <div
                                                        id="dropdownDots"
                                                        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600"
                                                    >
                                                        <ul
                                                            className="py-2 text-sm text-gray-700 dark:text-gray-200"
                                                            aria-labelledby="dropdownMenuIconButton"
                                                        >
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    View
                                                                    Submission
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Send
                                                                    reminder
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a
                                                                    href="#"
                                                                    className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                                                >
                                                                    Set
                                                                    expiration
                                                                    period
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </TabPanel>
                        </Tabs>
                    </div>
                </main>
            </Layout>
        </>
    );
}
