/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Layout from "../../../components/layout";
import Header from "../../../components/header";
import calendar from "../../../assets/calendar.png";
import { CircularProgressbar } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
import Revenuechart from "../../../components/revenuechart";
import Reportschart from "../../../components/reportschart";
import Minigraphs from "../../../components/minigraphs";
import Image from "next/image";

export default function Reports() {
    const percentage = 65;
    return (
        <>
            <Layout>
                <Head>
                    <title>Report</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] grow pb-10">
                    {/* Change props to suit page*/}
                    <Header title={"Mortgage Requests"} number={21} />
                    {/* Bottom menu */}
                    <div className="flex items-center h-[3.0625rem] bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">
                            Mortgage Requests/{" "}
                            <span className="text-black">Report</span>{" "}
                        </div>

                        <div>
                            <div>
                                <button
                                    type="button"
                                    className="px-3 py-2 text-xs font-medium text-center text-white bg-[#d0650d] rounded-md hover:bg-[#ee7613] focus:ring-4 focus:outline-none focus:ring-yellow-500 dark:bg-[#d0650d] dark:hover:bg-[#ee7613] dark:focus:ring-yellow-500"
                                >
                                    + Add Chart
                                </button>

                                <button
                                    type="button"
                                    className="text-[#D0650D] hover:text-white border m-3 border-yellow-700 hover:bg-[#d0650d] font-bold focus:ring-4 focus:outline-none focus:ring-[#d0650d] font-sm rounded-md text-sm px-2 py-1 text-center mr-2 mb-2 dark:border-yellow-700 dark:text-[#d0650d] dark:hover:text-yellow-700 dark:hover:bg-[#d0650d] dark:focus:ring-[#d0650d]"
                                >
                                    Export Data
                                </button>
                            </div>
                        </div>
                    </div>

                    <p className="text-sm font-semibold px-[5rem] py-6">
                        Here is the report for the day.
                    </p>

                    <div className="border bg-[] rounded-xl ml-[6%] mb-[5%] h-auto w-[90%]">
                        <div className="flex items-center mb-0 rounded-t-xl w-[100%]  bg-[] justify-between border-b px-[2rem] py-4">
                            <h6 className="font-bold pt-2">
                                Accounts Overview
                            </h6>
                            <section className="flex">
                                <Image
                                    src={calendar}
                                    width={15}
                                    height={50}
                                    alt={"calendar image"}
                                />
                                <p className="font-bold self-center pl-1 text-xs ">
                                    2022
                                </p>
                            </section>
                        </div>

                        <div className="flex rounded-md my-1">
                            <div className="w-[52%] h-[] shadow-md bg-[white] rounded-lg mr-2 my-1 border-2 ">
                                <h3 className="mt-7 text-[#58575F] text-[21px] ml-9 font-bold">
                                    Total Revenue
                                </h3>
                                <p className="mt-[0.0625rem] ml-9 font-bold text-3xl">
                                    GHC 100,000.00
                                </p>

                                <h6 className="mt-[2.1875rem] ml-9 text-[16px] text-[#58575F] font-bold ">
                                    Amount Loaned
                                </h6>
                                <p className="mt- ml-9 mb-0 font-bold tracking-tight text-[23px]">
                                    GHC 30,000.70
                                </p>

                                <div className="w-[100%] h-[57%] mb-0  ">
                                    <Revenuechart />
                                </div>
                            </div>

                            <div className="w-[22%] h-[40%] border-2 my-1 shadow-md bg-[white] rounded-lg ">
                                <h5 className="text-[1.3125rem] m-7 text-[#58575F] font-bold">
                                    Approval rate
                                </h5>
                                <div className="cursor-default w-[50%] mt-[20%] h-[] ml-[25%]">
                                    <CircularProgressbar
                                        value={percentage}
                                        text={`${percentage}%`}
                                        className="font-normal "
                                        styles={{
                                            path: {
                                                stroke: `rgba(208,101,13, ${
                                                    percentage / 100
                                                })`,
                                            },
                                            text: {
                                                fill: "#000",
                                                fontSize: "30px",
                                            },
                                        }}
                                    />
                                </div>
                                <p className="text-[21px] mb-[10%] mt-[20%] font-bold  ml-[15%]">
                                    GHC 30,000.70
                                </p>
                            </div>

                            <div className="mb-52 w-[22%] shadow-md h-[40%] ml-2 my-1 bg-gradient-to-br from-[#D0650D] via-[#d0650df3] to-[#f5b179] rounded-[7px] ">
                                <h5 className="text-white m-7 text-[1.3125rem] font-bold">
                                    Default rates
                                </h5>
                                <div className="cursor-default w-[50%] mt-[20%] h-[] ml-[25%] ">
                                    <CircularProgressbar
                                        value={percentage}
                                        text={`${percentage}%`}
                                        className="font-normal"
                                        styles={{
                                            path: {
                                                stroke: `rgba(255,255,255, ${
                                                    percentage / 100
                                                })`,
                                            },
                                            text: {
                                                fill: "#ffffff",
                                                fontSize: "30px",
                                            },
                                        }}
                                    />
                                </div>
                                <p className="text-white text-[21px] font-bold mb-[10%] ml-[15%] mt-[20%]">
                                    GHC 30,000.70
                                </p>
                            </div>
                        </div>

                        <div className="flex items-center mb-5 py-3 rounded justify-between h-[12%] bg-[#EBF0F0]">
                            <div
                                className="flex bg-white rounded-md w-[31%] h-[7.125rem]"
                                id="total clients"
                            >
                                <div className="m-6 mr-12">
                                    <h6 className="text-gray-500 text-sm font-medium">
                                        Total clients
                                    </h6>
                                    <p className="font-bold pt-2 text-lg">
                                        823,000
                                    </p>
                                </div>
                                <div className="w-[9.5625rem] h-[4.25rem] self-center">
                                    <Minigraphs />
                                </div>
                            </div>

                            <div
                                className="flex bg-white rounded-md w-[31%] h-[7.125rem] ml-4"
                                id="borrowers"
                            >
                                <div className="m-6 mr-12">
                                    <h6 className="text-gray-500 text-sm font-medium">
                                        Borrowers
                                    </h6>
                                    <p className="font-bold pt-2 text-lg">
                                        29,000
                                    </p>
                                </div>
                                <div className="w-[9.5625rem] h-[4.25rem] self-center">
                                    <Minigraphs />
                                </div>
                            </div>

                            <div
                                className="flex flex-col bg-white rounded-md w-[31%] mb-0 h-[7.125rem] ml-4"
                                id="loan status"
                            >
                                <h6 className="mt-5 ml-7 text-gray-500 text-sm font-medium">
                                    Loan Status
                                </h6>

                                <div className="flex pt-3">
                                    <section className="ml-[12%]">
                                        <span className="flex items-center text-sm font-medium text-[#965E00] dark:text-white">
                                            <span className="flex w-2.5 h-2.5 bg-[#965E00] rounded-full mr-1.5 flex-shrink-0"></span>
                                            Unpaid
                                        </span>
                                        <p className="text-lg font-bold text-center">
                                            200
                                        </p>
                                    </section>

                                    <section className="ml-[15%]">
                                        <span className="flex items-center text-sm font-medium text-[#D30000] dark:text-white">
                                            <span className="flex w-2.5 h-2.5 bg-[#D30000] rounded-full mr-1.5 flex-shrink-0"></span>
                                            Overdue
                                        </span>
                                        <p className="text-lg font-bold text-center">
                                            200
                                        </p>
                                    </section>

                                    <section className="ml-[15%]">
                                        <span className="flex items-center text-sm font-medium text-[#007F00] dark:text-white">
                                            <span className="flex w-2.5 h-2.5 bg-[#007F00] rounded-full mr-1.5 flex-shrink-0"></span>
                                            Paid
                                        </span>
                                        <p className="text-lg font-bold text-center">
                                            200
                                        </p>
                                    </section>
                                </div>
                            </div>
                        </div>

                        <div className="w-[100%] h-[600px]">
                            <Reportschart />
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    );
}
