/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Layout from "../../../components/layout";
import Header from "../../../components/header";

import closebutton from "../../../assets/close.png"


import Image from "next/image";

export default function Home() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Dashboard</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA]">
                    {/* Change props to suit page*/}
                    <Header
					title={"Mortgage Requests"}
					number={21}
				/>
                      {/* Bottom menu */}
                      <div className="flex items-center bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">Mortgage Requests/ Report</div>
                    
                    <div>

                    </div>
                    </div>


                    <p className= "text-sm font-semibold mx-8 px-8 py-6">Here is the report for the day.</p>


                    <div className="w-[643px] h-[667px] m-20 rounded-t-lg bg-white">
                    <section className="flex bg-[#D0650D] mb-[40] items-center w-[643px] h-[50px] rounded-t-lg">
                    <p className="mr-auto text-white font-bold ml-[20px]">Schedule Meeting</p>
                    <div className="flex rounded-full hover:bg-[#ee8b3a] w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
    <Image className=" self-center ml-[4.5px]" src={closebutton} width={10} alt={"close button"} />
</div>

                    </section>

        <form>
        <div className="mt-[40px] ml-10 mb-6">
    <label htmlFor="title" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title</label>
    <input type="text" id="title" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[#D0650D] focus:border-[#D0650D] block w-[564px] p-2.5 dark:bg-gray-700 placeholder- dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#D0650D] dark:focus:border-[#D0650D]" placeholder="Enter Meeting Title" required/>
</div>

<div className="flex ml-10 mb-6">
<section>
    


</section>



<section>  
<label htmlFor="platform" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Platform</label>
<select id="platform" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[#D0650D] focus:border-[#D0650D] block w-[286px] p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#D0650D] dark:focus:border-[#D0650D]" required>
  <option>Select Platform</option>
  <option>Zoom Meetings</option>
  <option>Google Meet</option>
  <option>Microsoft Teams</option>
  <option>In Person</option>
</select>
</section>
</div>

<div className="ml-10 mb-3">
    <label htmlFor="invites" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">People To Invite</label>
    <input type="text" id="invites" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[#D0650D] focus:border-[#D0650D] block w-[497px] p-2.5 dark:bg-gray-700 placeholder- dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#D0650D] dark:focus:border-[#D0650D]" placeholder="Enter email, separate by comma" required/>
</div>

<div className="flex ml-10 mb-5">
    <section>
    <div className="rounded-full text-white bg-[#FF9900] w-[40px] h-[40px] text-center text-[20px] ml-[15px] font-bold pt-1">JD</div>
    <p className="ml-5 text-[#2E2D37] font-semibold">John</p>
    </section>
    <section>
    <div className="rounded-full text-white bg-[#2B5E89] w-[40px] h-[40px] text-center text-[20px] ml-[15px] font-bold pt-1">IM</div>
    <p className="ml-6 font-semibold text-[#2E2D37]">Ian</p>
    </section>
</div>


<label htmlFor="comments" className="block mb-2 ml-10 text-sm font-medium text-gray-900 dark:text-white">Comment</label>
<textarea id="comments" rows={10} className="block p-2.5 ml-10 mb-auto w-[564px] h-[118px] text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-[#D0650D] focus:border-[#D0650D] dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-[#D0650D] dark:focus:border-[#D0650D]" placeholder="Enter comment"></textarea>

<div className="flex justify-end mr-[40px] mt-8">
<button type="button" className="text-[#D0650D] hover:text-[#D0650D] border border-[#D0650D] hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded w-[109px] text-sm px-9 py-1 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800">Cancel</button>


<button type="button" className="text-white bg-[#D0650D] hover:bg-[#ce7124] focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded w-[109px] text-sm px-9 py-1 mr-2 mb-2 dark:bg-[#D0650D] dark:hover:bg-[#ce7124] dark:focus:ring-gray-700 dark:border-gray-700">Save</button>

</div>

  </form>

    </div>
                </main>
            </Layout>
        </>
    );
}
