/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../assets/logo.png";
import Layout from "../../../components/layout";

type navbarProp = {
    name?: string;
    hostType?: string;
    joinDate?: string;
};

export default function Notifications(props: navbarProp) {
    const selectChange = (
        event: React.ChangeEvent<HTMLInputElement>,
        eventTarget: string
    ) => {
        const { value, checked } = event.target;

        console.log(`${value} is ${checked}`);
    };

    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>Notifications</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white mt-20 pl-5 w-[93%] rounded-lg border  pr-5  pb-5 ">
                        <div className="border-b pb-8 ">
                            <h3 className="pl-4 text-[#FA790F] text-2xl font-semibold pt-5 ">
                                Notifications
                            </h3>
                            <p className="pl-4 text-[#58575F] text-sm leading-[140%] font-normal pt-2  ">
                                You can customize your preferences for receiving
                                notifications from the app.
                            </p>
                        </div>

                        <div className="border-b pb-[3.1875rem]">
                            <h3 className="pl-4 pt-4 font-semibold text-[#FA790F]">
                                Security alerts
                            </h3>
                            <p className="font-normal pl-4  py-6 text-[#58575F] text-sm ">
                                You will only get enabled notifications
                            </p>

                            <div className="flex pl-4 text-[#04030F] font-normal text-sm flex-row justify-between mb-5">
                                <div>
                                    Email me whenever i encounter an unusual
                                    activity
                                </div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="1"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>

                            <div className="flex text-[#04030F] font-normal text-sm pl-4 flex-row justify-between mb-5">
                                <div>
                                    Email me whenever a new browser is used to
                                    sign in
                                </div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="2"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div className="border-b pb-[3.1875rem]">
                            <h3 className="pl-4 pt-4 font-semibold text-[#FA790F]">
                                Reminders
                            </h3>
                            <p className="pl-4 font-normal py-6 text-[#58575F] text-sm">
                                You will only get enabled notifications
                            </p>

                            <div className="flex flex-row pl-4 text-[#04030F] font-normal text-sm justify-between mb-5">
                                <div>Receive reminders of appointments</div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="3"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>
                            <div className="flex flex-row text-[#04030F] font-normal text-sm pl-4 justify-between mb-5">
                                <div>
                                    Notify me when subscription is about to
                                    exprire
                                </div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="4"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>
                            <div className="flex flex-row text-[#04030F] font-normal text-sm pl-4 justify-between mb-5">
                                <div>
                                    Notify me when subscription is about to
                                    exprire
                                </div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="5"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div className="pb-5">
                            <h3 className="pl-4 pt-4 font-semibold text-[#FA790F]">
                                General
                            </h3>
                            <p className="py-6 font-normal pl-4 text-[#58575F] text-sm">
                                You will only get enabled notifications
                            </p>
                            <div className="flex flex-row pl-4 text-[#04030F] font-normal text-sm justify-between mb-5">
                                <div>Notify me when there is a new request</div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="6"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>
                            <div className="flex flex-row pl-4 text-[#04030F] font-normal text-sm justify-between mb-5">
                                <div>
                                    Notify me when subscription is about to
                                    exprire
                                </div>
                                <div>
                                    <label className="relative inline-flex items-center cursor-pointer">
                                        <input
                                            type="checkbox"
                                            value="7"
                                            name="switch"
                                            onChange={(event) =>
                                                selectChange(
                                                    event,
                                                    event.target.tagName
                                                )
                                            }
                                            className="sr-only peer"
                                        />
                                        <div
                                            className="w-16 h-6 mr-4 bg-zinc-600 rounded-full peer 
                                        peer-checked:after:translate-x-11 peer-checked:after:border-white after:content-[''] 
                                        after:absolute after:top-0.5  after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all  
                                        peer-checked:bg-cyan-400"
                                        ></div>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <button
                            type="button"
                            className="text-white leading-5 text-sm ml-4 bg-[#FA790F] font-normal rounded px-4 py-2 "
                        >
                            Save changes
                        </button>
                    </div>
                </main>
            </Layout>
        </>
    );
}
