/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../assets/logo.png";
import Layout from "../../../components/layout";
import BillingAddress from "../../../components/manageSubscriptions/billingAddress";

export default function BillingInfo() {
    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>Billing Info</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white w-[93%] rounded-lg px-5 border mt-20 ">
                        <div className="pl-4 pb-5">
                            <h3 className="text-[#FA790F] pt-5 text-2xl font-semibold ">
                                Billing Address
                            </h3>
                            <p className="text-[#58575F] text-sm w-[47.1875rem] mt-2">
                                Changes to your billing information will take
                                effect starting with scheduled payment and will
                                be reflected on your next invoice
                            </p>
                        </div>

                        <div className="border-y pt-4">
                            <button
                                type="button"
                                className="text-[#FA790F] leading-5 ml-4 font-semibold  text-sm  border border-[#FA790F] rounded px-8 py-2"
                            >
                                Add new address
                            </button>

                            <div>
                                <BillingAddress
                                    location="Accra, Adenta Housing Down Road"
                                    postalCode="Postal code: 200591"
                                    region="Region: Greater Accra"
                                    digitalAddress="Digital address: AF-044-0001"
                                />
                            </div>
                            <div>
                                <BillingAddress location="Sekondi-Takoradi, Liberation Road" />
                            </div>
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    );
}
