/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../assets/logo.png";
import Layout from "../../../components/layout";
import InvoiceTable from "../../../components/manageSubscriptions/invoiceTable";

export default function Invoice() {
    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>Invoice</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white w-[93%] rounded-lg border px-5 mt-20">
                        <div className="border-b pb-5">
                            <h3 className="pl-4 text-[#FA790F] text-2xl font-semibold pt-5">
                                Invoice
                            </h3>
                            <p className="pl-4 text-[#58575F] text-sm leading-[140%] font-normal pt-2">
                                You can find all your order invoices here
                            </p>
                        </div>

                        <div className="mr-[3.4375rem] ml-4 mt-4 ">
                            <div className="relative overflow-x-auto bg-white sm:rounded-md">
                                <table className="w-full text-left text-sm text-gray-500 ">
                                    <thead className="bg-[#F0F0F0] text-xs text-[#747A80]">
                                        <tr>
                                            <th
                                                scope="col"
                                                className="pl-[2%] py-4"
                                            >
                                                #ID
                                            </th>
                                            <th
                                                scope="col"
                                                className="pl-[16%] py-4"
                                            >
                                                Date
                                            </th>
                                            <th
                                                scope="col"
                                                className="pl-[1%] py-4"
                                            >
                                                Price
                                            </th>
                                            <th
                                                scope="col"
                                                className="pl-[20%] py-4"
                                            >
                                                Status
                                            </th>
                                        </tr>
                                    </thead>

                                    <tbody className="text-left px-0">
                                        {/* First row */}
                                        <tr className="bg-white hover:bg-gray-50">
                                            <InvoiceTable
                                                id="#1111"
                                                date="23/01/2023, 10:45pm"
                                                price={30}
                                                status="Due"
                                            />
                                        </tr>

                                        {/* Second row */}
                                        <tr className="bg-white hover:bg-gray-50">
                                            <InvoiceTable
                                                id="#1112"
                                                date="23/01/2023, 10:45pm"
                                                price={30}
                                                status="Completed"
                                            />
                                        </tr>

                                        {/* Third row */}
                                        <tr className="bg-white hover:bg-gray-50">
                                            <InvoiceTable
                                                id="#1113"
                                                date="23/01/2023, 10:45pm"
                                                price={30}
                                                status="Completed"
                                            />
                                        </tr>

                                        {/* Fourth row */}
                                        <tr className="bg-white hover:bg-gray-50">
                                            <InvoiceTable
                                                id="#1114"
                                                date="23/01/2023, 10:45pm"
                                                price={30}
                                                status="Completed"
                                            />
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    );
}
