/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../assets/logo.png";
import Layout from "../../../components/layout";
import PaymentMethods from "../../../components/manageSubscriptions/paymentMethods";

export default function Payment() {
    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>Payment</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white px-5 w-[93%] pb-5 rounded-lg border  mt-20">
                        <div className="border-b pb-5">
                            <h3 className="pl-4 text-[#FA790F] text-2xl font-semibold pt-5">
                                Payment methods
                            </h3>
                            <p className="pl-4 text-[#58575F] text-sm leading-[140%] font-normal pt-2">
                                Your primary payment method is used by default.
                            </p>
                        </div>

                        <div className="border-b pt-4 ">
                            <button
                                type="button"
                                className="text-[#FA790F] leading-5 text-sm  border border-[#FA790F] ml-4 font-semibold rounded px-6 py-2"
                            >
                                Add payment method
                            </button>

                            <PaymentMethods
                                expiry="Expires in 10/2024"
                                type="Paypal express ending in 0000"
                            />

                            <PaymentMethods
                                expiry="Non-expiry"
                                type="MTN momo-0549010900"
                            />
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    );
}
