/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Header from "../../components/header";
import Layout from "../../components/layout";
import Link from "next/link";
import Image from "next/image";
import plus from "../../assets/plus.png";
import integration from "../../assets/integrations.png";
import SmallRegtangle, { Info } from "../../components/dashboardshapes";
import Bubble from "../../components/bubbles";
import { CircularProgressbar } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
import BarChart from "../../components/barChat";

export default function Dashbaord() {
    const percentage = 89;
    return (
        <>
            <Layout>
                <Head>
                    <title>Dashboard</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>

                <Header title={"Admin Dashboard"} number={21} />
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] grow">
                    {/* Bottom menu */}
                    <div className="flex items-center bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">Dashbaord</div>
                        <Link href={"#"} className="text-[#0052FF]">
                            Getting started
                        </Link>
                    </div>

                    <section className="px-[5rem] xg:px-[10rem]">
                        {/* Welconme messgae */}
                        <p className="py-4">Welcome to your dashboard🎉</p>
                        {/* First Row */}
                        <div className="grid grid-cols-4 gap-x-8 w-[90%] h-[8.75rem] mb-10">
                            <SmallRegtangle
                                number={230}
                                description={"Total Requests"}
                            />
                            <SmallRegtangle
                                number={"GHC 2300"}
                                description={"Total Money Sent"}
                            />
                            <SmallRegtangle
                                number={230}
                                description={"Total Requests"}
                            />
                            <div className="flex flex-col justify-center items-center basis-52 border rounded-lg bg-white shadow-[0_0_10px_rgba(0,0,0,0.07)]">
                                <p className="flex flex-row gap-4 mb-2">
                                    <Image src={plus} alt={""} />
                                    <Image src={integration} alt={""} />
                                </p>
                                <p className="font-normal text-xs text-slate-400">
                                    Add Integration
                                </p>
                            </div>
                        </div>

                        {/* Second Row */}
                        <div className="flex flex-row h-[19.376rem] mb-10">
                            <div className="flex flex-col w-[39%] items-center mr-2.5 justify-between py-6 border rounded-lg bg-white shadow-[0_4px_58px_rgba(0,0,0,0.04)]">
                                <p className="text-xl font-extrabold text-[#58575F] mr-10">
                                    Approval Rate
                                </p>
                                <div className="w-[8.1rem] h-[8.138rem]">
                                    <CircularProgressbar
                                        value={percentage}
                                        text={`${percentage}%`}
                                        className="font-normal "
                                        styles={{
                                            path: {
                                                stroke: `rgba(208,101,13, ${
                                                    percentage / 100
                                                })`,
                                            },
                                            text: {
                                                fill: "#000",
                                                fontSize: "30px",
                                            },
                                        }}
                                    />
                                </div>
                                <p className="text-2xl font-extrabold">
                                    GHC 30,000.70
                                </p>
                            </div>

                            <div className="gradient flex flex-col w-[38%] items-center mr-4 justify-between py-6 border rounded-lg bg-white shadow-[0_4px_58px_rgba(0,0,0,0.04)]">
                                <p className="text-xl font-extrabold text-white mr-10">
                                    Default Rate
                                </p>
                                <div className="w-[8.1rem] h-[8.138rem]">
                                    <CircularProgressbar
                                        value={percentage}
                                        text={`${percentage}%`}
                                        className="font-normal"
                                        styles={{
                                            path: {
                                                stroke: `rgba(255,255,255, ${
                                                    percentage / 100
                                                })`,
                                            },
                                            text: {
                                                fill: "#ffffff",
                                                fontSize: "30px",
                                            },
                                        }}
                                    />
                                </div>
                                <p className="text-2xl font-extrabold text-white">
                                    GHC 30,000.70
                                </p>
                            </div>
                            <div className="flex flex-col w-full justify-center col-span-2 items-center border rounded-lg bg-white shadow-[0_4px_58px_rgba(0,0,0,0.04)]">
                                <BarChart />
                            </div>
                        </div>

                        {/* Third row */}
                        <div className="h-[16.8125rem] mb-10 border rounded-lg bg-white px-4 shadow-[0_4px_20px_rgba(171,171,171,0.25)] overflow-auto">
                            <div className="flex flex-row justify-between px-5 py-5">
                                <p className="font-medium">
                                    Today's Pending Approvals
                                </p>
                                <Link
                                    href={"#"}
                                    className="text-[#0C17DC] underline"
                                >
                                    See all
                                </Link>
                            </div>

                            <div className="grid grid-cols-3 items-center">
                                <p className="text-[#747A80] text-sm font-bold flex justify-center">
                                    Name
                                </p>
                                <p className="text-[#747A80] text-sm font-bold flex justify-center">
                                    Amount requested
                                </p>
                            </div>

                            {/* Info */}
                            <Info
                                name={"Ama Yeboah"}
                                mail={"example@gmail.com"}
                                money={"GHC 3000.00"}
                                request={"23/01/2023"}
                                link={"/"}
                            />
                            <Info
                                name={"Ama Yeboah"}
                                mail={"example@gmail.com"}
                                money={"GHC 3000.00"}
                                request={"23/01/2023"}
                                link={"/"}
                            />
                        </div>

                        {/* Fourth row */}
                        <div className="h-[12.525rem] mb-10 border rounded-lg bg-white px-4 shadow-[0_4px_20px_rgba(171,171,171,0.25)]">
                            <div className="flex justify-between px-5 pt-5">
                                <p className="font-medium">Report Summary</p>
                                <Link
                                    href={"#"}
                                    className="text-[#0C17DC] underline"
                                >
                                    See in detail
                                </Link>
                            </div>
                            <div className="flex justify-between px-7 pt-10">
                                <div className="basis-[17.375rem] h-20 border boreder-[#FEFEFE] rounded-xl flex">
                                    <div className="w-[5%] h-full bg-[#3ABBD4] border rounded-l-xl">
                                        {/* Blue color  */}
                                    </div>

                                    <div className="flex flex-col mt-2 w-full px-2 h-6">
                                        <div className="flex flex-row justify-between">
                                            <p className="text-[#747A80]">
                                                Loan Status
                                            </p>
                                            <Bubble name={"Pending"} />
                                        </div>
                                        <p className="flex item-center justify-center mt-2 text-2xl font-semibold">
                                            240
                                        </p>
                                    </div>
                                </div>

                                <div className="basis-[17.375rem] h-20 border boreder-[#FEFEFE] rounded-xl flex">
                                    <div className="w-[5%] h-full bg-[#3ABBD4] border rounded-l-xl">
                                        {/* Blue color  */}
                                    </div>

                                    <div className="flex flex-col mt-2 w-full px-2 h-6">
                                        <div className="flex flex-row justify-between">
                                            <p className="text-[#747A80]">
                                                Loan Status
                                            </p>
                                            <Bubble name={"Paid"} />
                                        </div>
                                        <p className="flex item-center justify-center mt-2 text-2xl font-semibold">
                                            240
                                        </p>
                                    </div>
                                </div>

                                <div className="basis-[17.375rem] h-20 border boreder-[#FEFEFE] rounded-xl flex">
                                    <div className="w-[5%] h-full bg-[#3ABBD4] border rounded-l-xl">
                                        {/* Blue color  */}
                                    </div>

                                    <div className="flex flex-col mt-2 w-full px-2 h-6">
                                        <div className="flex flex-row justify-between">
                                            <p className="text-[#747A80]">
                                                Loan Status
                                            </p>
                                            <Bubble name={"Rejected"} />
                                        </div>
                                        <p className="flex item-center justify-center mt-2 text-2xl font-semibold">
                                            240
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </main>
            </Layout>
        </>
    );
}
