/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Layout from "../../../../components/layout";
import Header from "../../../../components/header";
import closebutton from "../../../../assets/close.png";
import Image from "next/image";

export default function Home() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Dashboard</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA]">
                    {/* Change props to suit page*/}
                    <Header title={"Mortgage Requests"} number={21} />
                    {/* Bottom menu */}
                    <div className="flex items-center bg-white justify-between border-b px-[5rem] py-4">
                        <div className="text-[#FA790F]">
                            Mortgage Requests/ Report
                        </div>

                        <div></div>
                    </div>

                    <p className="text-sm font-semibold mx-8 px-8 py-6">
                        Here is the report for the day.
                    </p>

                    {/* Password confirmation prompt 1 */}
                    <div className="rounded-lg w-[543px] h-[246px] border-2 m-6 bg-white">
                        <section className="rounded-t-lg items-center flex w-[539px] h-12 bg-[#D0650D] ">
                            <p className="text-white text center pl-6 mr-auto">
                                Password
                            </p>
                            <div className="flex rounded-full w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
                                <Image
                                    className=" self-center ml-[4.5px]"
                                    src={closebutton}
                                    width={10}
                                    alt={"close button"}
                                />
                            </div>
                        </section>

                        <div className="mb-[9px] pt-9">
                            <label
                                htmlFor="password"
                                className="block mb-4 text-sm font-medium text-black text-center dark:text-white"
                            >
                                Enter password below to confirm
                            </label>
                            <input
                                type="password"
                                id="password"
                                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-[437px] ml-[50px] p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder="Enter Password here"
                                required
                            />
                        </div>

                        <hr className="h-px mb-1 mt bg-gray-200 border-0 dark:bg-gray-700" />

                        <div className="flex mt-[10px] mr-11 justify-end">
                            <button
                                type="button"
                                className="text-[#7B7B6E] hover:text-white border border-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-3.5 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                            >
                                Cancel
                            </button>

                            <button
                                type="button"
                                className="text-white bg-[#ABABAF] hover:bg-gray-500 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                            >
                                Accept
                            </button>
                        </div>
                    </div>

                    {/* Password confirmation prompt 2 */}
                    <div className="rounded-lg mb-20 max-w-[543px] h-[246px] border-2 m-6 bg-white">
                        <section className="rounded-t-lg items-center flex max-w-[539px] h-12 bg-[#D0650D] ">
                            <p className="text-white text center pl-6 mr-auto">
                                Password
                            </p>
                            <div className="flex rounded-full w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
                                <Image
                                    className=" self-center ml-[4.5px]"
                                    src={closebutton}
                                    width={10}
                                    alt={"close button"}
                                />
                            </div>
                        </section>

                        <div className="mb-[9px] pt-9">
                            <label
                                htmlFor="password"
                                className="block mb-4 text-sm font-medium text-black text-center dark:text-white"
                            >
                                Enter password below to confirm
                            </label>
                            <input
                                type="password"
                                id="password"
                                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-[437px] ml-[50px] p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder=""
                                required
                            />
                        </div>

                        <hr className="h-px mb-1 mt bg-gray-200 border-0 dark:bg-gray-700" />

                        <div className="flex mt-[10px] mr-11 justify-end">
                            <button
                                type="button"
                                className="text-[#D0650D] hover:text-[#D0650D] border border-[#D0650D] hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-[#fb8f37a4] font-medium rounded-lg text-sm px-5 py-3.5 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                            >
                                Cancel
                            </button>

                            <button
                                type="button"
                                className="text-white bg-[#D0650D] hover:bg-[#FB8F37] focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                            >
                                Accept
                            </button>
                        </div>
                    </div>

                    {/* password confirmation prompt 3 */}
                    <div
                        id=""
                        className="rounded-lg mb-20 max-w-[543px] h-[246px] border-2 m-6 bg-white"
                    >
                        <section className="rounded-t-lg items-center flex max-w-[539px] h-12 bg-[#D0650D] ">
                            <p className="text-white text center pl-6 mr-auto">
                                Password
                            </p>
                            <div className="flex rounded-full w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
                                <Image
                                    className=" self-center ml-[4.5px]"
                                    src={closebutton}
                                    width={10}
                                    alt={"close button"}
                                />
                            </div>
                        </section>

                        <div className="mb-[9px] pt-9">
                            <label
                                htmlFor="password"
                                className="block mb-4 text-sm font-medium text-black text-center dark:text-white"
                            >
                                Enter password below to confirm
                            </label>
                            <input
                                type="password"
                                id="password"
                                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-[437px] ml-[50px] p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder=""
                                required
                            />
                        </div>

                        <hr className="h-px mb-1 mt bg-gray-200 border-0 dark:bg-gray-700" />

                        <div className="flex mt-[10px] mr-11 justify-end">
                            <button
                                type="button"
                                className="text-[#D0650D] hover:text-[#D0650D] border border-[#D0650D] hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-[#fb8f37a4] font-medium rounded-lg text-sm px-5 py-3.5 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                            >
                                Cancel
                            </button>

                            <button
                                type="button"
                                className="text-white bg-[#D0650D] hover:bg-[#FB8F37] focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                            >
                                Decline
                            </button>
                        </div>
                    </div>

                    {/* Password confirmation prompt 4 */}
                    <div className="rounded-lg mb-20 w-[543px] h-[246px] border-2 m-6 bg-white">
                        <section className="rounded-t-lg items-center flex w-[539px] h-12 bg-[#D0650D] ">
                            <p className="text-white text center pl-6 mr-auto">
                                Password
                            </p>
                            <div className="flex rounded-full w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
                                <Image
                                    className=" self-center ml-[4.5px]"
                                    src={closebutton}
                                    width={10}
                                    alt={"close button"}
                                />
                            </div>
                        </section>

                        <div className="mb-[9px] pt-9">
                            <label
                                htmlFor="password"
                                className="block mb-4 text-sm font-medium text-black text-center dark:text-white"
                            >
                                Enter password below to confirm
                            </label>
                            <input
                                type="password"
                                id="password"
                                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-[437px] ml-[50px] p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder="Enter Password here"
                                required
                            />
                        </div>

                        <hr className="h-px mb-1 mt bg-gray-200 border-0 dark:bg-gray-700" />

                        <div className="flex mt-[10px] mr-11 justify-end">
                            <button
                                type="button"
                                className="text-[#7B7B6E] hover:text-white border border-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-3.5 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                            >
                                Cancel
                            </button>

                            <button
                                type="button"
                                className="text-white bg-[#87878d] hover:bg-gray-500 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                            >
                                Decline
                            </button>
                        </div>
                    </div>

                    {/* pre-approve loan request prompt */}
                    <div
                        id="pre-approve-request"
                        className="rounded-lg mb-20 max-w-[543px] h-[246px] border-2 m-6 bg-white"
                    >
                        <section className="rounded-t-lg items-center flex max-w-[539px] h-12 bg-[#D0650D] ">
                            <p className="text-white text center pl-6 mr-auto">
                                Pre-approve Request
                            </p>
                            <div className="flex rounded-full w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
                                <Image
                                    className=" self-center ml-[4.5px]"
                                    src={closebutton}
                                    width={10}
                                    alt={"close button"}
                                />
                            </div>
                        </section>

                        <p className="text-center font-semibold text-base pt-11">
                            Are you sure you want to pre-approve this loan
                            request?{" "}
                        </p>

                        <hr className="h-px mt-12 mb-1 mt bg-gray-200 border-0 dark:bg-gray-700" />

                        <section className="flex">
                            <div className="flex items-center ml-4 mr-auto">
                                <input
                                    checked
                                    id="orange-checkbox"
                                    type="checkbox"
                                    value=""
                                    className="w-4 h-4 text-orange-500 bg-gray-100 border-gray-300 rounded focus:ring-orange-500 dark:focus:ring-orange-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                                />
                                <label
                                    htmlFor="orange-checkbox"
                                    className="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                                >
                                    Do not show this again
                                </label>
                            </div>

                            <div className="flex mt-[10px] mr-1 justify-end">
                                <button
                                    type="button"
                                    className="text-[#D0650D] hover:text-[#D0650D] border border-[#D0650D] hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-[#fb8f37a4] font-medium rounded-lg text-sm px-5 py-2 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                                >
                                    Cancel action
                                </button>

                                <button
                                    type="button"
                                    className="text-white bg-[#D0650D] hover:bg-[#FB8F37] focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                                >
                                    Yes, accept
                                </button>
                            </div>
                        </section>
                    </div>

                    {/* decline request prompt */}
                    <div
                        id="decline-request"
                        className="rounded-lg mb-20 max-w-[543px] h-[246px] border-2 m-6 bg-white"
                    >
                        <section className="rounded-t-lg items-center flex max-w-[539px] h-12 bg-[#D0650D] ">
                            <p className="text-white text center pl-6 mr-auto">
                                Decline Request
                            </p>
                            <div className="flex rounded-full w-[20px] h-[20px] mr-4 bg-[#FB8F37]">
                                <Image
                                    className=" self-center ml-[4.5px]"
                                    src={closebutton}
                                    width={10}
                                    alt={"close button"}
                                />
                            </div>
                        </section>

                        <p className="text-center font-semibold text-sm max-w-[500px] pl-7 pt-11">
                            Are you sure you want to decline this request?
                            Performing this action means user is denied to have
                            access to your organization’s loan.{" "}
                        </p>

                        <hr className="h-px mt-12 mb-1 mt bg-gray-200 border-0 dark:bg-gray-700" />

                        <section className="flex">
                            <div className="flex items-center ml-4 mr-auto">
                                <input
                                    checked
                                    id="orange-checkbox"
                                    type="checkbox"
                                    value=""
                                    className="w-4 h-4 text-orange-500 bg-gray-100 border-gray-300 rounded focus:ring-orange-500 dark:focus:ring-orange-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                                />
                                <label
                                    htmlFor="orange-checkbox"
                                    className="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                                >
                                    Do not show this again
                                </label>
                            </div>

                            <div className="flex mt-[10px] mr-1 justify-end">
                                <button
                                    type="button"
                                    className="text-[#D0650D] hover:text-[#D0650D] border border-[#D0650D] hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-[#fb8f37a4] font-medium rounded-lg text-sm px-5 py-2 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                                >
                                    Yes, decline
                                </button>

                                <button
                                    type="button"
                                    className="text-white bg-[#D0650D] hover:bg-[#FB8F37] focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                                >
                                    No, do not decline
                                </button>
                            </div>
                        </section>
                    </div>
                </main>
            </Layout>
        </>
    );
}
