/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Header from "../../../components/header";
import Layout from "../../../components/layout";
import Image from "next/image";
import googleform from "../../../assets/googleform.png";
import googlesheet from "../../../assets/google sheets.png";
import slack from "../../../assets/slack.png";

export default function Integrations() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Integrations</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>

                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] grow pb-10">
                    {/* Change props to suit page*/}
                    <Header title={"Configuration"} number={21} />
                    {/* Bottom menu */}
                    <div className="flex items-center h-[3.0625rem] mb-0 bg-white justify-between border-b px-[5rem] py-4">
                        <div className="font-normal leading-[1.4rem] text-base text-[#FA790F]">
                            Configuration/{"  "}
                            <span className="text-black">Integrations</span>
                        </div>

                        <div>
                            <button
                                type="button"
                                className="px-3 py-2 text-xs font-medium text-center text-white bg-[#d0650d] rounded hover:bg-[#ee7613] focus:ring-4 focus:outline-none focus:ring-yellow-500 dark:bg-[#d0650d] dark:hover:bg-[#ee7613] dark:focus:ring-yellow-500"
                            >
                                + Add Integration
                            </button>
                        </div>
                    </div>

                    <section className="bg-[#FAFAFA] pt-3 mt-0 mb-0 px-[5rem]">
                        <div className="h-[6.4375rem] pb-0 mb-0 w-full">
                            <p className="text-[#58575F] font-normal leading-[140%] text-[14px] pt-6">
                                Add Integrations to your website
                            </p>
                        </div>

                        <div className="flex flex-wrap gap-x-8">
                            <div className="bg-[#FFFFFF] mb-20 mt-2 rounded-lg pt-0 shadow-md h-[16.81rem] w-[13.93rem]">
                                <Image
                                    className="ml-[2.312rem] mb-0 pt-[1.875rem]"
                                    src={googleform}
                                    width={149}
                                    alt={"Google Forms logo"}
                                />

                                <h5 className="text-center pt-5 mb-0 text-sm font-black leading-[150%]">
                                    Google Form
                                </h5>
                                <p className="text-center pt-2 text-sm font-normal leading-[140%] text-[#58575F]">
                                    Fill out form
                                </p>

                                <button
                                    type="button"
                                    className="ml-[4.5rem] text-[#D0650D] mt-5 hover:text-white border border-[#D0650D] hover:bg-[#D0650D] focus:ring-4 focus:outline-none focus:ring-[#D0650D] font-medium rounded-md text-sm px-3 py-1 text-center mr-2 mb-2 dark:border-[#D0650D] dark:text-[#D0650D] dark:hover:text-white dark:hover:bg-[#D0650D] dark:focus:ring-[#D0650D]"
                                >
                                    Connect
                                </button>
                            </div>

                            <div className="bg-[#FFFFFF] mb-20 mt-2 rounded-lg pt-0 shadow-md h-[16.81rem] w-[13.93rem]">
                                <Image
                                    className="ml-[4.75rem] mb-0 pt-[1.875rem]"
                                    src={googlesheet}
                                    width={70}
                                    alt={"Google Sheets logo"}
                                />

                                <h5 className="text-center pt-[1.625rem] mb-0 text-sm font-black leading-[150%]">
                                    Google Sheet
                                </h5>
                                <p className="text-center pt-2 text-sm font-normal leading-[140%] text-[#58575F]">
                                    Create Spreadsheets
                                </p>

                                <button
                                    type="button"
                                    className="ml-[4.5rem] text-[#D0650D] mt-[1.67rem] hover:text-white border border-[#D0650D] hover:bg-[#D0650D] focus:ring-4 focus:outline-none focus:ring-[#D0650D] font-medium rounded-md text-sm px-3 py-1 text-center mr-2 mb-2 dark:border-[#D0650D] dark:text-[#D0650D] dark:hover:text-white dark:hover:bg-[#D0650D] dark:focus:ring-[#D0650D]"
                                >
                                    Connect
                                </button>
                            </div>

                            <div className="bg-[#FFFFFF] mb-20 mt-2 rounded-lg pt-0 shadow-md h-[16.81rem] w-[13.93rem]">
                                <Image
                                    className="ml-[4.4375rem] mb-0 pt-9"
                                    src={slack}
                                    width={81}
                                    alt={"Slack logo"}
                                />

                                <h5 className="text-center pt-9 mb-0 text-sm font-black leading-[150%]">
                                    Slack
                                </h5>
                                <p className="text-center pt-2 text-sm font-normal leading-[140%] text-[#58575F]">
                                    Channel Communication
                                </p>

                                <button
                                    type="button"
                                    className="ml-[4.5rem] text-[#D0650D] mt-[1.35rem] hover:text-white border border-[#D0650D] hover:bg-[#D0650D] focus:ring-4 focus:outline-none focus:ring-[#D0650D] font-medium rounded-md text-sm px-3 py-1 text-center mr-2 mb-2 dark:border-[#D0650D] dark:text-[#D0650D] dark:hover:text-white dark:hover:bg-[#D0650D] dark:focus:ring-[#D0650D]"
                                >
                                    Connect
                                </button>
                            </div>
                        </div>
                    </section>
                </main>
            </Layout>
        </>
    );
}
