/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../assets/logo.png"
import { Formik, Field, ErrorMessage } from "formik";
import * as Yup from "yup";


type ForgotPasswordProp = {
    email: string;
}

export default function forgotPassword(props:ForgotPasswordProp) {
    return (
        <>
        
                <Head>
                    <title>Forgot Password</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>

                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] xg:min-h-screen">
                    {/* Bottom menu */}
                    <section className="flex">
                    <div className="w-[40%]  h-[1024px] border ">
                    <Formik<ForgotPasswordProp>
                    initialValues={{
                        email: "",

                       
                    }}
                    validationSchema={Yup.object({
                        email: Yup.string()
                        .email('Invalid email').email('invalid email')
                            .required("Required field"),
                        
                    })}
                    onSubmit={(values) => {
                        alert(JSON.stringify(values));
                    }}
                >
                    {({
                        handleSubmit,
                        values,
                        handleChange,
                        setFieldValue,
                    }) => (

                    <form
                    onSubmit={handleSubmit}
                    >
                    <Image className="w-[4.1875rem] h-[2.5625rem] mt-[5%] ml-[4.5rem] " src={logo} alt="Logo" />

                    <p className="font-extrabold text-[2.5rem] leading-[3.75rem] text-center mt-[35%] text-[#181818] ">Forgot Password?</p>

                    <p className="text-[#747A80] ml-[15%] text-center font-light w-[425px] text-sm mt-[1.125rem] leading-[140%]">Enter your email below, you will receive an email with instructions on how to reset your password in a few minutes. </p>

                    
                    <div className="ml-[15%] mt-[3%] mb-6">
                     <Field type="email" id="email" className="bg-gray-50 border border-gray-300 placeholder:text-[#ABABAF] text-gray-900 text-sm rounded focus:ring-blue-500 focus:border-blue-500 block w-[80%] p-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter email" onChange={handleChange} value={values.email} />
                     <p className="font-medium text-red-700">
                    <ErrorMessage name="email"/>
                    </p>
                    </div>


    <button type="button" className="focus:outline-none text-[1.25rem] text-white bg-[#FA790F] font-medium rounded px-7 py-2 ml-[15%] w-[68%] mb-2 mt-7">Submit</button>
                    

                    

                    <p className="text-[#818187] mt-6 text-center text-sm">Go back to <a href="" className="text-[#0129F9] hover:underline">Sign In</a></p>

                    </form>
                    )}
                    </Formik>


                    </div>



<div className="bg-signin bg-cover w-[60%] bg-no-repeat h-[1024px]">
    <p className="text-[64px] ml-[25%] leading-[3.75rem] mt-[41.5%] text-white font-bold w-[32.25rem]">Let us guide you home.</p>
    <p className="text-white ml-[25%] font-medium w-[512px] text-base pt-6 leading-[1.4rem]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fring</p>
</div>



                    </section>
                </main>
        </>
    );
}
