/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../assets/logo.png";
import Link from "next/link";
import { Formik, Field, ErrorMessage } from "formik";
import * as Yup from "yup";

type ForgotPasswordProp = {
    email: string;
};

export default function forgotPassword(props: ForgotPasswordProp) {
    return (
        <>
            <Head>
                <title>Forgot Password</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>

            {/* Code goes into the main tag */}
            <main className="bg-[#FAFAFA] xg:min-h-screen">
                {/* Bottom menu */}
                <section className="flex">
                    <div className="w-[60%]  h-screen border ">
                        <Formik<ForgotPasswordProp>
                            initialValues={{
                                email: "",
                            }}
                            validationSchema={Yup.object({
                                email: Yup.string()
                                    .email("Invalid email")
                                    .email("invalid email")
                                    .required("Required field"),
                            })}
                            onSubmit={(values) => {
                                alert(JSON.stringify(values));
                            }}
                        >
                            {({
                                handleSubmit,
                                values,
                                handleChange,
                                setFieldValue,
                            }) => (
                                <form onSubmit={handleSubmit}>
                                    <Image
                                        className="w-[4.1875rem] h-[2.5625rem] mt-[5%] ml-[4.5rem] "
                                        src={logo}
                                        alt="Logo"
                                    />

                                    <p className="font-extrabold text-[2.5rem] leading-[3.75rem] text-center mt-[13%] text-[#181818]">
                                        Forgot Password?
                                    </p>

                                    <p className="text-[#747A80] text-center ml-[25%] font-light w-[49%] text-sm mt-[1.125rem] leading-[140%]">
                                        Enter your email below, you will receive
                                        an email with instructions on how to
                                        reset your password in a few minutes.{" "}
                                    </p>

                                    <div className="ml-[25%] mt-[3%] mb-6">
                                        <Field
                                            type="email"
                                            id="email"
                                            className="bg-gray-50 border border-gray-300 placeholder:text-[#ABABAF] text-gray-900 text-sm rounded focus:ring-blue-500 focus:border-blue-500 block w-[65%] p-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                            placeholder="Enter email"
                                            onChange={handleChange}
                                            value={values.email}
                                        />
                                        <p className="font-medium text-sm   mt-1 text-red-700">
                                            <ErrorMessage name="email" />
                                        </p>
                                    </div>

                                    <Link href={"/views/Homeowner/mailSent"}>
                                        <button
                                            type="button"
                                            className="focus:outline-none text-[1.25rem] text-white bg-[#FA790F] font-medium rounded py-2 ml-[25%] w-[49%] mb-2 mt-7"
                                        >
                                            Submit
                                        </button>
                                    </Link>

                                    <p className="text-[#818187] mt-6 text-center text-sm">
                                        Go back to{" "}
                                        <Link
                                            href={"/"}
                                            className="text-[#0129F9] hover:underline"
                                        >
                                            Sign In
                                        </Link>
                                    </p>
                                </form>
                            )}
                        </Formik>
                    </div>

                    <div className="bg-signin bg-contain w-[40%] bg-no-repeat h-screen">
                        <p className="text-[64px] ml-[10%] leading-[3.75rem] mt-[41.5%] text-white font-bold w-[70%]">
                            Let us guide you home.
                        </p>
                        <p className="text-white ml-[10%] font-medium w-[70%] text-base pt-6 leading-[1.4rem]">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Ut et massa mi. Aliquam in hendrerit urna.
                            Pellentesque sit amet sapien fring
                        </p>
                    </div>
                </section>
            </main>
        </>
    );
}
