/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Formik, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
import logo from "../assets/logo.png"
import googlelogo from "../assets/googlelogo.png"
import Link from "next/link";




type SignInProp = {
    email?: string;
    password?: string;
};

export default function SignIn(props: SignInProp) {
    
    return (
        <>
                <Head>
                    <title>Sign In</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>

                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] xg:min-h-screen">
                    {/* Bottom menu */}
                    <section className="flex">
                   <div className="w-[40%] h-[1024px] border">
                    <Formik<SignInProp>
                    initialValues={{
                        email: "",
                        password: "",
                       
                    }}
                    validationSchema={Yup.object({
                        email: Yup.string()
                            .max(5, "Must be 40 characters or less")
                            .required("Required field"),
                        password: Yup.string()
                            .required("Required field"),
                        
                    })}
                    onSubmit={(values) => {
                        alert(JSON.stringify(values));
                    }}
                >
                    {({
                        handleSubmit,
                        values,
                        handleChange,
                        setFieldValue,
                    }) => (
                    <form
                    onSubmit={handleSubmit}
                    
                    >
                        <div>
                    <Image className="w-[4.1875rem] h-[2.5625rem] mt-[5%] ml-[4.5rem] " src={logo} alt="Logo" />

                    <p className="font-extrabold text-[2.5rem] leading-[3.75rem] pt-[26%] text-center mt-[15%] text-[#181818] ">Welcome Back!</p>
                    <p className="text-[#747A80] text-center font-light text-sm mt-[3%] leading-[140%]">Sign into your account</p>
                                
                                
                                <div className="mt-[4%] ml-[15%]">
                                    <Field
                                        type="email"
                                        id="email"
                                        className="border placeholder:text-[#ABABAF] border-gray-300 text-gray-900 text-sm rounded focus:ring-blue-500 focus:border-blue-500 block w-[80%] p-2.5"
                                        placeholder="Enter email"
                                        value={values.email}
                                        onChange={handleChange}
                                    />
                                    <p className="font-medium text-xs text-red-700">
                                        <ErrorMessage name="email" />
                                    </p>
                                </div>


                                <div className="ml-[15%] mt-[3.5%] ">
                                    <Field
                                        type="password"
                                        id="password"
                                        className="border placeholder:text-[#ABABAF] border-gray-300 text-gray-900 text-sm rounded focus:ring-blue-500 focus:border-blue-500 block w-[80%] p-2.5"
                                        placeholder="Enter password here"
                                        value={values.password}
                                        onChange={handleChange}
                                    />
                                    <p className="font-medium text-xs text-red-700">
                                        <ErrorMessage name="password" />
                                    </p>
                                </div>

                                <div className="flex mt-[5%]">
                    <div className="flex items-center mr-auto ml-[15%] h-5">
      <input id="remember" type="checkbox" value="" className="w-4 h-4 border border-gray-300 rounded bg-gray-50 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-offset-gray-800" required />
      <label htmlFor="remember" className="ml-2 text-sm font-normal text-[#818187] dark:text-gray-300">Remember me</label>
    </div>
        
        <a href="" className="underline underline-offset-2 text-xs mr-[17.5%] text-[#0129F9]" >Forgot Password?</a>


    </div>

<Link href={"./views/homeowner"}>
    <button type="button" className="focus:outline-none text-[1.25rem] text-white bg-[#FA790F] font-medium rounded py-2 ml-[15%] w-[68%] mb-2 mt-10">Sign In</button>

    <p className="text-[#818187] mt-6 text-center text-sm">Don’t have an account? <a href="" className="text-[#0129F9] hover:underline">Sign Up</a></p>
    </Link>

                


<div className="mt-[12%]">
<button type="button" className="text-black border rounded-tl-lg mt-6 rounded-br-lg w-[68%] border-[#DADADA] focus:outline-none text-xs py-2.5 text-center inline-flex justify-center font-normal items-center ml-[15%] mr-2 mb-2">
  <Image className="mr-[14px]" src={googlelogo} alt={""} />
  Sign in with Google
</button>
</div>


                                
                    </div>
                    </form>
                    )}
                    </Formik>
                    </div>
                    
                    


<div className="bg-signin w-[60%]  bg-cover bg-no-repeat h-[1024px]">
    <p className="text-[64px] mt-[56%] ml-[] leading-[3.75rem] text text-white font-bold w-[32.25rem]">Let us guide you home.</p>
    <p className="text-white pt-2 w-[512px] font-medium text-base leading-[1.4rem]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fring</p>
</div>
              </section>
                </main>
        </>
    );
}
