/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Header from "../../../../components/header";
import Layout from "../../../../components/layout";
import Link from "next/link";
import { Percentages } from "../../../../components/mortgageheader";

export default function RatesForm() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Rates</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>

                <Header title={"Mortgage Requests"} number={5} />
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}
                    <div className="flex items-center bg-white justify-between border-b px-[5rem] py-2">
                        <div className="text-[#FA790F]">
                            Morgage Requests
                            <span className="text-black">/Rates</span>
                        </div>
                        <Link href={""}>
                            <button className="bg-[#D0650D] text-white rounded-md p-1 px-3 mr-2 hover:shadow-md hover:shadow-[#D0650D]">
                                Update
                            </button>

                            <button className="border border-[#D0650D] text-[#D0650D] rounded-md p-1 px-6 mr-2 hover:text-orange-300">
                                Cancel
                            </button>
                        </Link>
                    </div>

                    {/* Bottom Menu */}
                    <div className="mt-[30px] px-[5rem]">
                        <div className="grid grid-cols-3 items-center h-16 bg-[#FDF2EA]">
                            <p className="text-[#747A80] text-sm font-bold pl-[15%]">
                                Product
                            </p>
                            <p className="text-[#747A80] text-sm font-bold pl-[20%]">
                                Interest rate
                            </p>
                            <p className="text-[#747A80] text-sm font-bold flex justify-center pl-[20%]">
                                Annual Percentage Rate
                            </p>
                        </div>
                        <Percentages
                            product2={"20-year fixed-rate"}
                            modified2={"Last modified: 23/01/2023"}
                        />
                    </div>
                </main>
            </Layout>
        </>
    );
}
