/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../../assets/logo.png";
import Layout from "../../../../components/layout";
import Link from "next/link";

export default function DeleteProfile() {
    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>Delete Profile</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white w-[93%] border pb-5 rounded-lg mt-20 px-5 ">
                        <div className="border-b">
                            <h3 className="pt-4 font-semibold text-2xl leading-[2.0625rem] text-[#FA790F] pl-4 ">
                                Delete your profile
                            </h3>
                            <p className="pl-4 pb-8 text-[#58575F] pt-2 font-normal text-sm leading-[140%]">
                                Delete or close your account permanently
                            </p>
                        </div>

                        <div className="pl-4 pt-4">
                            <h6 className="text-[#FA790F] text-xl font-medium ">
                                Warning
                            </h6>
                            <p className="text-[#58575F] pt-2 font-normal text-sm leading-[140%] w-[553px]">
                                This action cannot be undone and all your data,
                                including your properties, settings, and account
                                information will be permanently deleted
                            </p>
                        </div>

                        <Link
                            href={"/views/accountSettings/DeleteProfile/reason"}
                        >
                            <button
                                type="button"
                                className="text-[#D30000] mt-12 leading-5 text-xs border border-[#D30000] font-semibold  rounded px-6 py-1.5"
                            >
                                Delete my account
                            </button>
                        </Link>
                    </div>
                </main>
            </Layout>
        </>
    );
}
