/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../../assets/logo.png";
import Layout from "../../../../components/layout";
import { Formik, Field, ErrorMessage } from "formik";
import Link from "next/link";
import * as Yup from "yup";

export default function DeleteProfile() {
    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>Delete Profile</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white mt-20 rounded-lg border w-[93%]">
                        <Formik
                            initialValues={{
                                option1: "",
                            }}
                            validationSchema={Yup.object({})}
                            onSubmit={(values) => {
                                alert(JSON.stringify(values));
                            }}
                        >
                            {({
                                handleSubmit,
                                values,
                                handleChange,
                                setFieldValue,
                            }) => (
                                <form
                                    onSubmit={async (values) => {
                                        await new Promise((r) =>
                                            setTimeout(r, 500)
                                        );
                                        alert(JSON.stringify(values, null, 2));
                                    }}
                                    className="bg-white px-5 rounded-lg pb-10"
                                >
                                    <div className="border-b pb-5">
                                        <h3 className="pl-4 text-[#FA790F] text-2xl font-semibold pt-5 ">
                                            Delete your profile
                                        </h3>
                                        <p className="pl-4 text-[#58575F] text-sm leading-[140%] font-normal pt-2  ">
                                            Delete or close your account
                                            permanently
                                        </p>
                                    </div>

                                    <div className="pb-12 ">
                                        <h6 className="pl-4 pt-4 text-xl  font-semibold text-[#FA790F]">
                                            Warning
                                        </h6>
                                        <p className="text-[#58575F] pt-2 pl-4 font-normal text-sm leading-[140%] w-[553px]">
                                            Please provide a reason why you are
                                            closing your account
                                        </p>
                                    </div>

                                    {/* Deletion reasons options */}
                                    <div className="pl-4">
                                        <div className="flex pb-3 items-center">
                                            <Field
                                                id="option1"
                                                type="radio"
                                                name="option1"
                                                className="w-4 h-4 text-[#FA790F] border-[#FA790F] focus:ring-0"
                                                value="option1"
                                                onChange={handleChange}
                                            />
                                            <label
                                                htmlFor="option1"
                                                className="block ml-2 text-sm font-  text-[#58575F]"
                                            >
                                                I have found another service
                                            </label>
                                        </div>

                                        <div className="flex pb-3 items-center">
                                            <Field
                                                id="option2"
                                                type="radio"
                                                name="option1"
                                                className="w-4 h-4 text-[#FA790F] border-[#FA790F] focus:ring-0"
                                                value="option2"
                                                onChange={handleChange}
                                            />
                                            <label
                                                htmlFor="option2"
                                                className="block ml-2 text-sm font-normal leading-[140%]   text-[#58575F]"
                                            >
                                                I have successfully sold or
                                                rented out my property and no
                                                longer need the app.
                                            </label>
                                        </div>

                                        <div className="flex pb-3 items-center">
                                            <Field
                                                id="option3"
                                                type="radio"
                                                name="option1"
                                                className="w-4 h-4 text-[#FA790F] border-[#FA790F] focus:ring-0"
                                                value="option3"
                                                onChange={handleChange}
                                            />
                                            <label
                                                htmlFor="option3"
                                                className="block ml-2 text-sm font-normal leading-[140%]  text-[#58575F]"
                                            >
                                                I have encountered problems with
                                                the app, such as technical
                                                issues or poor customer service.
                                            </label>
                                        </div>

                                        <div className="flex pb-3 items-center">
                                            <Field
                                                id="option4"
                                                type="radio"
                                                name="option1"
                                                className="w-4 h-4 text-[#FA790F] border-[#FA790F] focus:ring-0"
                                                value="option4"
                                                onChange={handleChange}
                                            />
                                            <label
                                                htmlFor="option4"
                                                className="block ml-2 text-sm font-normal leading-[140%]  text-[#58575F]"
                                            >
                                                I have encountered problems with
                                                the app, such as technical
                                                issues or poor customer service.
                                            </label>
                                        </div>

                                        <div className="flex pb-3 items-center">
                                            <Field
                                                id="option5"
                                                type="radio"
                                                name="option1"
                                                className="w-4 h-4 text-[#FA790F] border-[#FA790F] focus:ring-0"
                                                value="option5"
                                                onChange={handleChange}
                                            />
                                            <label
                                                htmlFor="option5"
                                                className="block ml-2 text-sm font-normal leading-[140%]  text-[#58575F]"
                                            >
                                                No longer own the property and
                                                cannot offer it for rent or
                                                sale.
                                            </label>
                                        </div>

                                        <div className="flex pb-3 items-center">
                                            <Field
                                                id="option6"
                                                type="radio"
                                                name="option1"
                                                className="w-4 h-4 text-[#FA790F]  border-[#FA790F] focus:ring-0"
                                                value="option6"
                                                onChange={handleChange}
                                            />
                                            <label
                                                htmlFor="option6"
                                                className="block ml-2 text-sm font-normal leading-[140%]  text-[#58575F]"
                                            >
                                                Other reasons not specified
                                            </label>
                                        </div>
                                    </div>

                                    <Link
                                        href={
                                            "/views/accountSettings/DeleteProfile/feedback"
                                        }
                                    >
                                        <button
                                            type="button"
                                            className="text-[#D30000] mt-8 ml-4 leading-5 text-base  border border-[#D30000] font-medium  rounded px-6 py-2.5"
                                        >
                                            Continue
                                        </button>
                                    </Link>
                                </form>
                            )}
                        </Formik>
                    </div>
                </main>
            </Layout>
        </>
    );
}
