/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../../../assets/logo.png";
import Layout from "../../../../../../components/layout";
import Link from "next/link";

export default function ProPlans() {
    return (
        <>
            <div className="bg-white h-[97px] w-full">
                <div className="w-[75px] h-[74px] ml-[5.56%] mt-[29px]">
                    <Image src={logo} alt="" />
                </div>
            </div>

            <Layout>
                <Head>
                    <title>My Subscriptions</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                </Head>
                {/* Code goes into the main tag */}
                <main className="bg-[#FAFAFA] min-h-screen">
                    {/* Bottom menu */}

                    <div className="bg-white mt-20 px-[2.5rem]">
                        <div className="border-b">
                            <h3>Delete your profile</h3>
                            <p>Delete or close your account permanently</p>
                        </div>

                        <div>
                            <h6>Warning</h6>
                            <p className="text-[#58575F] font-normal text-sm leading-[140%] w-[553px]">
                                This action cannot be undone and all your data,
                                including your properties, settings, and account
                                information will be permanently deleted
                            </p>
                        </div>

                        <Link
                            href={"/views/accountSettings/DeleteProfile/reason"}
                        >
                            <button
                                type="button"
                                className="text-[#D30000] leading-5 text-xs border border-[#D30000] font-normal rounded px-3 py-1"
                            >
                                Delete my account
                            </button>
                        </Link>
                    </div>
                </main>
            </Layout>
        </>
    );
}
